tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "asimov"
brew "atomicparsley"
brew "bash"
brew "bat"
brew "unbound"
brew "ffmpeg"
brew "gh"
brew "git"
brew "git-flow"
brew "htop"
brew "imagemagick"
brew "mackup"
brew "mas"
brew "node@14"
brew "pwgen"
brew "rclone"
brew "reattach-to-user-namespace"
brew "rename"
brew "ruby"
brew "ssh-copy-id"
brew "tmux"
brew "tree"
brew "vercel-cli"
brew "watchman"
brew "wget"
brew "wifi-password"
brew "wp-cli"
brew "wp-cli-completion"
brew "youtube-dl"
cask "authy"
cask "battle-net"
cask "caffeine"
cask "discord"
cask "figma"
cask "firefox"
cask "font-ia-writer-duo"
cask "font-ia-writer-duospace"
cask "font-ia-writer-mono"
cask "font-ia-writer-quattro"
cask "font-smoothing-adjuster"
cask "google-chrome"
cask "insomnia"
cask "kapitainsky-rclone-browser"
cask "logitech-firmwareupdatetool"
cask "logitech-options"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "notion"
cask "obs"
cask "obsidian"
cask "openemu"
cask "phoenix"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "raycast"
cask "slack"
cask "sourcetree"
cask "tableplus"
cask "the-unarchiver"
cask "transmission"
cask "transmit"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zoom"
mas "AdGuard for Safari", id: 1440147259
mas "Collected", id: 1511343960
mas "Developer", id: 640199958
mas "GarageBand", id: 682658836
mas "Hush", id: 1544743900
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Refined GitHub", id: 1519867270
mas "Telegram", id: 747648890
mas "Things", id: 904280696
mas "Xcode", id: 497799835
